import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Activity, ArrowUpRight, Download, RefreshCw, Ticket, IndianRupee, ShoppingBag, XCircle } from "lucide-react";
import { api } from "./api";
import type { ApiResponse } from "./types";
type Daily = {day:string; bookings:number; tickets:number; amount:number; cancelled:number};
type Analytics = {totals:Omit<Daily,"day">; trend:Daily[]; averageBookingValue:number; cancellationRate:number; topEvents:{id:string;title:string;tickets:number;amount:string}[]; generatedAt:string; paymentMode:string};
type Metrics = {requests:number;serverErrors:number;p95Ms:number;p50Ms:number;errorRate:number;uptimeSeconds:number;scope:string};
const money = (n:number|string) => new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n));
export function AnalyticsDashboard({admin=false}:{admin?:boolean}) {
  const [days,setDays]=useState(30); const scope=admin?"admin":"organizer";
  const report=useQuery({queryKey:[scope,"analytics",days],queryFn:()=>api.get<ApiResponse<Analytics>>(`/${scope}/analytics`,{params:{days}}).then(r=>r.data.data),refetchInterval:30000});
  const metrics=useQuery({queryKey:["admin","metrics"],queryFn:()=>api.get<ApiResponse<Metrics>>("/admin/metrics").then(r=>r.data.data),enabled:admin,refetchInterval:30000});
  const data=report.data;
  function download() { if(!data)return; const rows=[["Date (UTC)","Confirmed bookings","Tickets","Booking value INR","Cancelled or refunded"],...data.trend.map(d=>[d.day,d.bookings,d.tickets,d.amount,d.cancelled])]; const url=URL.createObjectURL(new Blob([rows.map(r=>r.join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`evently-${scope}-${days}-days.csv`;a.click();URL.revokeObjectURL(url); }
  const max=Math.max(1,...(data?.trend.map(d=>d.amount)??[]));
  return <div className="container-page py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">{admin?"Platform intelligence":"Your organizer workspace"}</p><h1 className="mt-3 text-4xl">A clearer view of your growth.</h1><p className="mt-3 text-slate-500">Track bookings, discover your best events and plan what comes next.</p></div><Link to={admin?"/admin/events":"/organizer/events/new"} className="btn-primary gap-2">{admin?"Manage events":"Create event"}<ArrowUpRight size={18}/></Link></div>
    <div className="my-8 flex flex-wrap items-center justify-between gap-4"><div className="flex gap-1 rounded-full border bg-white p-1">{[7,30,90].map(n=><button key={n} aria-pressed={days===n} className={`rounded-full px-5 py-2 text-sm font-bold ${days===n?"bg-night text-white":"text-slate-500"}`} onClick={()=>setDays(n)}>{n} days</button>)}</div><div className="flex gap-2"><button aria-label="Refresh analytics" disabled={report.isFetching} className="btn-secondary" onClick={()=>{void report.refetch();if(admin)void metrics.refetch();}}><RefreshCw size={16}/></button><button disabled={!data} className="btn-secondary gap-2" onClick={download}><Download size={16}/>Export CSV</button></div></div>
    {report.isPending?<div className="card p-12" role="status">Loading your analytics?</div>:report.isError?<div className="card p-12" role="alert">Analytics could not be loaded. Use refresh to try again.</div>:data&&<>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{label:"Booking value",value:money(data.totals.amount),note:"Simulated checkout ? INR",Icon:IndianRupee},{label:"Tickets booked",value:data.totals.tickets,note:"Confirmed tickets in this period",Icon:Ticket},{label:"Confirmed bookings",value:data.totals.bookings,note:`${money(data.averageBookingValue)} average value`,Icon:ShoppingBag},{label:"Cancellation rate",value:`${data.cancellationRate.toFixed(1)}%`,note:`${data.totals.cancelled} cancelled or refunded`,Icon:XCircle}].map(({label,value,note,Icon})=><div key={label} className="card p-6"><div className="flex items-center justify-between text-sm text-slate-500">{label}<Icon size={19} className="text-brand-600"/></div><p className="mt-5 text-3xl font-extrabold tabular-nums">{value}</p><p className="mt-3 text-xs text-slate-500">{note}</p></div>)}</div>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1.6fr_1fr]"><section className="card min-w-0 p-6 sm:p-8"><div className="flex items-center justify-between"><h2 className="text-xl">Booking activity</h2><span className="text-xs text-slate-500">Daily value ? INR ? UTC</span></div><p className="mt-2 text-sm text-slate-500">{data.totals.bookings?"See when your audience is showing up.":"Your first booking will start the story here."}</p><div className="analytics-chart" role="img" aria-label={`Daily booking value over ${days} days. Total ${money(data.totals.amount)}. Exact values in the daily data table.`}>{data.trend.map(d=><div key={d.day} className="chart-column" title={`${d.day}: ${money(d.amount)}, ${d.tickets} tickets`}><div style={{height:`${d.amount/max*100}%`,minHeight:d.amount?4:2}} className={d.amount?"chart-bar":"chart-zero"}/></div>)}</div><div className="mt-3 flex justify-between text-xs text-slate-400"><span>{data.trend[0]?.day}</span><span>{data.trend.at(-1)?.day}</span></div></section>
      <section className="card p-6 sm:p-8"><p className="eyebrow">The crowd favorites</p><h2 className="mt-2 text-xl">Top performing events</h2>{data.topEvents.length?data.topEvents.map((event,i)=><div key={event.id} className="mt-5 flex items-center gap-3 border-b pb-5 last:border-0"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-brand-50 text-sm font-bold text-brand-700">0{i+1}</span><div className="min-w-0 flex-1"><p className="truncate font-bold" title={event.title}>{event.title}</p><p className="mt-1 text-xs text-slate-500">{event.tickets} tickets</p></div><span className="text-sm font-bold">{money(event.amount)}</span></div>):<p className="mt-10 text-sm leading-7 text-slate-500">No confirmed bookings in this period. Share your published events to bring your first attendees in.</p>}</section></div>
      <details className="card mt-6 p-6"><summary className="cursor-pointer font-bold">Explore daily data</summary><div className="mt-4 max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Date (UTC)","Bookings","Tickets","Value","Cancelled / refunded"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.trend.map(d=><tr key={d.day} className="border-t"><td className="p-3">{d.day}</td><td className="p-3">{d.bookings}</td><td className="p-3">{d.tickets}</td><td className="p-3">{money(d.amount)}</td><td className="p-3">{d.cancelled}</td></tr>)}</tbody></table></div></details>
      <p className="mt-5 text-xs leading-6 text-slate-500">Updated {new Date(data.generatedAt).toLocaleTimeString()} ? Refreshes every 30 seconds. Bookings created in the selected UTC period, grouped by their current status. {data.paymentMode}.</p>
    </>}
    {admin&&<section className="card mt-8 p-6"><h2 className="flex items-center gap-2 text-xl"><Activity size={20}/>API performance</h2>{metrics.data?<><div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4">{[["Completed requests",metrics.data.requests],["p95 latency",`${metrics.data.p95Ms} ms`],["Server error rate",`${metrics.data.errorRate}%`],["Process uptime",`${Math.floor(metrics.data.uptimeSeconds/60)} min`]].map(([k,v])=><div key={k}><p className="text-xs text-slate-500">{k}</p><p className="mt-2 text-2xl font-bold">{v}</p></div>)}</div><p className="mt-5 text-xs text-slate-500">{metrics.data.scope}. Resets on restart; this is not a load-capacity guarantee.</p></>:<p className="mt-4 text-sm text-slate-500">{metrics.isError?"Performance data unavailable. Try refresh.":"Loading performance data?"}</p>}</section>}
  </div>;
}
